Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
Traceback (most recent call last):
  File "../heuristic_comparison-v1.py", line 3, in <module>
    from scipy.spatial import uniform, expon, poisson
ImportError: cannot import name 'uniform' from 'scipy.spatial' (/n/home03/junulee/.conda/envs/junulee_env1/lib/python3.7/site-packages/scipy/spatial/__init__.py)
